version: 'v3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: restaurant
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
volumes:
  db_data: